var societylist = [{id: "PFJ7BKE0E7",
name: "香港中文大學新亞書院學生會物理系系會"}
,{id: "Z3A866WZAR",
name: "香港中文大學新亞書院歷史學系系會"}
,{id: "BA29FSGU1T",
name: "香港中文大學新亞書院學生會演講及辯論學會" }
,{id: "H99LU3HZ1Z",
name: "香港中文大學新亞書院林錦權詠春拳術學會"}
,{id: "RDYK0XNON0",
name: "香港中文大學新亞書院學生會國樂會"}
,{id: "GXWBQ7T9CM",
name: "香港中文大學新亞書院那打素護理學院院會"}
,{id: "8185QXM31G",
name: "香港中文大學新亞書院漂書會"}
,{id: "QKS19SCPTI",
name: "香港中文大學藝術系系會"}
,{id: "J5L5A3KYUP",
name: "香港中文大學新亞書院學生會天文學會"}
,{id: "D9PR1NXNZY",
name: "香港中文大學新亞書院數學系系會"}
,{id: "8VKM0Q9GKX",
name: "香港中文大學新亞書院社會服務團"}
,{id: "1TF2UMDYE0",
name: "香港中文大學新亞書院經濟學系系會"}
,{id: "INE1DEAG1M",
name: "香港中文大學新亞書院學生會新亞劇社"}
,{id: "K8R5YD1CIL",
name: "香港中文大學新亞書院學生會醫學系系會"}
,{id: "1N7W2OFGGF",
name: "香港中文大學新亞書院扶輪青年服務團"}
,{id: "Q9TC0C0H8R",
name: "香港中文大學新亞書院內地生聯合會"}
,{id: "HKYXQSS5SC",
name: "香港中文大學新亞書院國術會"}
,{id: "F2UF5PC3SH",
name: "香港中文大學新亞書院社會工作學系系會"}
,{id: "YR9SM0NTIJ",
name: "香港中文大學新亞書院學生會社會學系系會"}
,{id: "JWTPHATKKU",
name: "香港中文大學新亞書院樂隊學會"}
,{id: "JIUIGSRBQN",
name: "香港中文大學新亞書院學生會統計系系會"}
,{id: "6J1YVGVKUE",
name: "香港中文大學新亞書院化學系系會"}
,{id: "69KB83P6DU",
name: "香港中文大學新亞書院學生會國際演講協會"}
,{id: "OQ2ETR2HVQ",
name: "香港中文大學新亞書院中國語文及文學系系會"}
,{id: "1ZKC1S7LI9",
name: "香港中文大學新亞書院英文系系會"}
,{id: "2FIE7U3XBO",
name: "香港中文大學新亞書院學生會人類學系系會"}
,{id: "DX6XIYZQVO",
name: "香港中文大學新亞書院工商管理學會"}]
